<?php

namespace AppBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllStudents()
    {
        return $this->createQueryBuilder('s')
            ->join('s.user','user')
            ->join('s.classnumber','grade')
            ->orderBy('grade.classnumber*1, grade.classnumber, s.lastname', 'ASC')
            ->getQuery()
            ->getResult();
    }
}