<?php

namespace AppBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeacherRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllTeachers()
    {
        return $this->createQueryBuilder('t')
            ->select('t.firstname, t.lastname, t.dateofbirth, t.gender, u.email, g.classnumber')
            ->leftJoin('t.user','u')
            ->leftJoin('t.grade','g')
            ->orderBy('t.lastname', 'ASC')
            ->getQuery()
            ->getResult();
    }
}